name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
          submodules: true

      - name: Remove git information from destination repository
        run: |
          mkdir dest.git
          cp -r source/* dest.git/
          cd dest.git
          rm -rf .git
      
      - name: Zip folder and save
        run: |
          mkdir -p Arduino-py32
          cp -r dest.git/* Arduino-py32/
          zip -r py32-${GITHUB_REF#refs/tags/}.zip Arduino-py32

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true
      - name: test
        run: |
          
      - name: Send repository_dispatch event to package json
        run: |
          curl -X POST https://api.github.com/repos/wemos/Arduino-pack-json-ci/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.USER_TOKEN }} \
          --data '{"event_type": "AirMCU"}'